### ISSUE TITLE
Vue3 compability

### ISSUE THREAD

**Issue by Mikolaj-Graja** [artus9033/chartjs-plugin-dragdata#111] opened 2022-12-12 10:22 UTC
Events are not working on Vue3 (composition api)

Example: 
```
const chartPlugins = [{
        id: 'mousedownCatcher',
        dragData: {
          round: 1,
          showTooltip: true,
          onDragStart: function (e, datasetIndex, index, value) {
            console.log(e)
          },
          onDrag: function (e, datasetIndex, index, value) {
            e.target.style.cursor = 'grabbing'
            console.log(e, datasetIndex, index, value)
          },
          onDragEnd: function (e, datasetIndex, index, value) {
            e.target.style.cursor = 'default'
            console.log(datasetIndex, index, value)
          },
        }
  }]

  const draggableChart = new Chart('draggableChart', {
        type: 'line',
        data: chartData,
        options: chartOptions,
        plugins: chartPlugins
  })
```
      
      + dragData: true on datasets in chartData

Result: no console logs, no changes in chart behaviour on click/ drag etc.

Plugin installed by npm

**Comment by chrispahm** [comment] 2022-12-12 13:04
Hey @Mikolaj-Graja,

Thanks for raising an issue. As always, I'd need a reproducible example on jsFiddle / Codesandbox etc. before having a deeper look.

**Comment by bitbytebit1** [comment] 2023-05-13 02:05
Can confirm I'm seeing the same issue: https://stackblitz.com/edit/nuxt-starter-2tb3jw?file=app.vue

**Comment by bitbytebit1** [comment] 2023-05-13 19:13
Got it working: https://stackblitz.com/edit/nuxt-starter-2tb3jw?file=app.vue

**Comment by artus9033** [comment] 2024-08-10 14:57
Since @bitbytebit1's last comment with MWE demonstrates that Vue works properly, I'm closing this issue.

**Closed by artus9033** 2024-08-10 14:57 UTC
