### ISSUE TITLE
Import package doesn't work: `Cannot read properties of undefined`

### ISSUE THREAD

**Issue by skyporter** [artus9033/chartjs-plugin-dragdata#127] opened 2023-10-31 19:56 UTC
**Describe the bug**
Importing the library (with webpack) throw an error `Uncaught TypeError: Cannot read properties of undefined (reading 'Chart')`

versions:
- dragdata => 2.2.5
- chartjs => 3.9.1

**To Reproduce**
```js
// application.js
import Chart from "chart.js/auto"
import "chartjs-plugin-dragdata"
```

**Comment by artus9033** [comment] 2024-07-26 16:14
Hi @skyporter, I finally found time to look at this recently but can't reproduce this with a clean Webpack setup, neither using 2.2.5 nor the current `master`. Could you provide a MRE repo?

**Comment by artus9033** [comment] 2024-07-28 18:31
Closing this as non-reproducible, but I'll reopen this provided an MRE is provided.

**Closed by artus9033** 2024-07-28 18:31 UTC
Labels: non-reproducible
